debug: false
uuid: 77ed76e4-75e1-4f22-82f5-99f3d6874221
token_id: OGRKWxtKH45OQZpi
token: v1FoL8mZWxl3GjcvMb3XazQ9O0a67iFNsi7y57oOPVU4Hm8imqkGMyOgougfZl0n
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
  upload_limit: 100
system:
  root_directory: /var/www/afterreload/.wings
  data: /var/www/afterreload/.wings/data
  log_directory: /var/www/afterreload/.wings/logs
  archive_directory: /var/www/afterreload/.wings/archives
  backup_directory: /var/www/afterreload/.wings/backups
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.afterreload.com'
